apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-deployment
  labels:
    app: usuario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuario
  template:
    metadata:
      labels:
        app: usuario
    spec:
      containers:
      - name: usuario
        image: alexxus/ms-prueba-usuario:v1
        ports:
        - containerPort: 3212
        env:
        - name: DB_HOST
          value: "clase2-semi1.cctockmoifnj.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: "DB_PASSWORD"
          value: "AgAzjSglkmJY6823uFCQ"
        - name: "DATABASE"
          value: "rds_prueba"