apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-config
data:
  env.js: |
    window.__env = {
      USUARIO_API: "http://aa5a395580167470a8c0c4c5dad81177-699102477.us-east-1.elb.amazonaws.com",
      MENSAJE_API: "http://afc69a3d184e545cb9626383545ca8e0-172412157.us-east-1.elb.amazonaws.com"
    };
