apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      role: front
  template:
    metadata:
      labels:
        role: front
    spec:
      containers:
      - name: cliente
        image: alexxus/frontss1:v5
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/assets/env.js
          subPath: env.js
      volumes:
      - name: config-volume
        configMap:
          name: angular-config
          items:
            - key: env.js
              path: env.js